# Generated by Django 4.2.6 on 2023-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("skills", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
