# Generated by Django 4.2.6 on 2023-10-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="home", name="name",),
    ]
