# Generated by Django 4.2.6 on 2023-10-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_home_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="home", name="skills",),
    ]
