# Generated by Django 4.2.6 on 2023-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_home_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
