# Generated by Django 4.2.6 on 2023-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="image",
            field=models.ImageField(blank=True, upload_to="home/"),
        ),
    ]
