# Generated by Django 4.2.6 on 2023-10-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_about_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=10)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("period", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("stack", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(model_name="home", name="image",),
    ]
