# Generated by Django 4.2.6 on 2023-10-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_projects_remove_home_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="about", name="subtitle",),
        migrations.RemoveField(model_name="about", name="title",),
    ]
