# Generated by Django 4.2.6 on 2023-10-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_about_subtitle_remove_about_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
