# Generated by Django 4.2.6 on 2023-10-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_about_subtitle_about_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="about", name="subtitle",),
        migrations.RemoveField(model_name="about", name="title",),
    ]
