# Generated by Django 4.2.6 on 2023-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_about_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwiperContent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="swiper/"),
                ),
            ],
        ),
        migrations.RenameModel(old_name="Projects", new_name="Project",),
    ]
