# Generated by Django 4.2.6 on 2023-10-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_image"),
    ]

    operations = [
        migrations.DeleteModel(name="SwiperContent",),
    ]
